---
# Source: eyal/templates/service.yaml
kind: Service     
apiVersion: v1     
metadata:
  name: exam-app-service 
  labels:
    
    generator: helm
    date: 2026-06-14
    name: exam-app
spec:
  selector:
    
    generator: helm
    date: 2026-06-14
    name: exam-app
  type: ClusterIP

  ports:         
  - name: http   
    protocol: 
    port: 8000
    targetPort: 8000
---
# Source: eyal/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-app-deploy
  labels:
    
    generator: helm
    date: 2026-06-14
    name: exam-app
spec:
  selector: 
    matchLabels:
      
      generator: helm
      date: 2026-06-14
      name: exam-app
  replicas: 2  
  template:
    metadata:
      labels:
        
        generator: helm
        date: 2026-06-14
        name: exam-app
    spec:
      containers:
      - name: exam-app 
        image: kfire312/exam-app:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
# Source: eyal/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  exam-app-ingress
  labels:
    
    generator: helm
    date: 2026-06-14
    name: exam-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  exam-app-service
                port:
                  number: 8000
